skip_branch_with_pr: true

version: '{build}'
init:
  # Set "build version number" to "short-commit-hash" or when tagged to "tag name" (Travis style)
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true")
      {
        Update-AppveyorBuild -Version "$env:APPVEYOR_REPO_TAG_NAME"
      }
      else
      {
        Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_COMMIT.substring(0,7))"
      }

install:
  - cinst InnoSetup -y
  - C:\Python36\Scripts\pip install -r requirements.txt
  - C:\Python36-x64\Scripts\pip install -r requirements.txt

build_script:
  - C:\Python36\python .\scripts\windows\update-version-info.py
  - C:\Python36\Scripts\pyinstaller --onefile .\git-xltrail-diff.py --name git-xltrail-diff-x86.exe --version-file .\scripts\windows\git-xltrail-version-info.py --icon .\scripts\windows\git-xltrail-logo.ico
  - mv dist\git-xltrail-diff-x86.exe git-xltrail-diff-x86.exe
  - C:\Python36-x64\Scripts\pyinstaller --onefile .\git-xltrail-diff.py --name git-xltrail-diff-x64.exe --version-file .\scripts\windows\git-xltrail-version-info.py --icon .\scripts\windows\git-xltrail-logo.ico
  - mv dist\git-xltrail-diff-x64.exe git-xltrail-diff-x64.exe
  - C:\Python36\Scripts\pyinstaller --onefile .\git-xltrail.py --name git-xltrail-x86.exe --version-file .\scripts\windows\git-xltrail-version-info.py --icon .\scripts\windows\git-xltrail-logo.ico
  - mv dist\git-xltrail-x86.exe git-xltrail-x86.exe
  - C:\Python36-x64\Scripts\pyinstaller --onefile .\git-xltrail.py --name git-xltrail-x64.exe --version-file .\scripts\windows\git-xltrail-version-info.py --icon .\scripts\windows\git-xltrail-logo.ico
  - mv dist\git-xltrail-x64.exe git-xltrail-x64.exe

after_build:
  - iscc scripts\windows\inno-setup-git-xltrail-installer.iss
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "false")
      {
        Rename-Item -Path "git-xltrail-windows-0.0.0.exe" -NewName "git-xltrail-windows-$($env:APPVEYOR_REPO_COMMIT.substring(0,7)).exe"
      }
  

artifacts:
  - path: git-xltrail-windows-*.exe
  - path: git-xltrail-x86.exe
  - path: git-xltrail-x64.exe
  - path: git-xltrail-diff-x86.exe
  - path: git-xltrail-diff-x64.exe

deploy:
- provider: GitHub
  release: $(APPVEYOR_REPO_TAG_NAME)
  description: 'Git xltrail $(APPVEYOR_REPO_TAG_NAME)'
  auth_token:
    secure: u1oi+34ucFzW+B5tKlGUMP2NjPISw4G61InbYVF3qYq6onAC4+rA92XRn+aDhMEW
  artifact: git-xltrail-windows-*.exe
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true

# on_finish:
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))