image: Visual Studio 2017
skip_branch_with_pr: true

version: '{build}'
init:
  # Set "build version number" to "short-commit-hash" or when tagged to "tag name" (Travis style)
  - cmd: SET PATH=C:\Program Files (x86)\Windows Kits\8.1\bin\x64\;%PATH%
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true")
      {
        Update-AppveyorBuild -Version "$env:APPVEYOR_REPO_TAG_NAME"
      }
      else
      {
        Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_COMMIT.substring(0,7))"
      }

install:
  - cinst InnoSetup -y
  - nuget install secure-file -ExcludeVersion
  - cd excel-addin
  - echo %cd%
  - nuget restore
  - cd ..
  - secure-file\tools\secure-file -decrypt scripts\windows\key.p12.enc -secret %secure%
  - C:\Python36\Scripts\pip install -r requirements.txt
  - C:\Python36-x64\Scripts\pip install -r requirements.txt

build_script:
  - cd excel-addin
  - echo %cd%
  - msbuild /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /p:Configuration=Release
  - cd ..
  - C:\Python36\python .\scripts\windows\update-version-info.py
  - C:\Python36\Scripts\pyinstaller --onefile .\src\diff.py --name git-xltrail-diff-x86.exe --version-file .\scripts\windows\git-xltrail-version-info.py --icon .\scripts\windows\git-xltrail-logo.ico --add-data .\src\xltrail-core.dll;.
  - mv dist\git-xltrail-diff-x86.exe git-xltrail-diff-x86.exe
  - C:\Python36-x64\Scripts\pyinstaller --onefile .\src\diff.py --name git-xltrail-diff-x64.exe --version-file .\scripts\windows\git-xltrail-version-info.py --icon .\scripts\windows\git-xltrail-logo.ico --add-data .\src\xltrail-core.dll;.
  - mv dist\git-xltrail-diff-x64.exe git-xltrail-diff-x64.exe
  - C:\Python36\Scripts\pyinstaller --onefile .\src\merge.py --name git-xltrail-merge-x86.exe --version-file .\scripts\windows\git-xltrail-version-info.py --icon .\scripts\windows\git-xltrail-logo.ico --add-data .\src\xltrail-core.dll;.
  - mv dist\git-xltrail-merge-x86.exe git-xltrail-merge-x86.exe
  - C:\Python36-x64\Scripts\pyinstaller --onefile .\src\merge.py --name git-xltrail-merge-x64.exe --version-file .\scripts\windows\git-xltrail-version-info.py --icon .\scripts\windows\git-xltrail-logo.ico --add-data .\src\xltrail-core.dll;.
  - mv dist\git-xltrail-merge-x64.exe git-xltrail-merge-x64.exe
  - C:\Python36\Scripts\pyinstaller --onefile .\src\cli.py --name git-xltrail-x86.exe --version-file .\scripts\windows\git-xltrail-version-info.py --icon .\scripts\windows\git-xltrail-logo.ico --add-data .\src\xltrail-core.dll;.
  - mv dist\git-xltrail-x86.exe git-xltrail-x86.exe
  - C:\Python36-x64\Scripts\pyinstaller --onefile .\src\cli.py --name git-xltrail-x64.exe --version-file .\scripts\windows\git-xltrail-version-info.py --icon .\scripts\windows\git-xltrail-logo.ico --add-data .\src\xltrail-core.dll;.
  - mv dist\git-xltrail-x64.exe git-xltrail-x64.exe

after_build:
  - xcopy "%APPVEYOR_BUILD_FOLDER%\excel-addin\packages\ExcelDna.AddIn.0.34.6\tools\ExcelDna.xll" "%APPVEYOR_BUILD_FOLDER%\excel-addin\Addin\bin\Release\xltrail.xll*" /C /Y
  - xcopy "%APPVEYOR_BUILD_FOLDER%\excel-addin\Addin\bin\Release\xltrail.dna" "%APPVEYOR_BUILD_FOLDER%\excel-addin\Addin\bin\Release\xltrail64.dna*" /C /Y
  - xcopy "%APPVEYOR_BUILD_FOLDER%\excel-addin\packages\ExcelDna.AddIn.0.34.6\tools\ExcelDna64.xll" "%APPVEYOR_BUILD_FOLDER%\excel-addin\Addin\bin\Release\xltrail64.xll*" /C /Y
  - xcopy "%APPVEYOR_BUILD_FOLDER%\excel-addin\packages\ExcelDna.AddIn.0.34.6\tools\ExcelDnaPack.exe" "%APPVEYOR_BUILD_FOLDER%\excel-addin\Addin\bin\Release\xltrail.dna" /Y
  - xcopy "%APPVEYOR_BUILD_FOLDER%\excel-addin\packages\ExcelDna.AddIn.0.34.6\tools\ExcelDnaPack.exe" "%APPVEYOR_BUILD_FOLDER%\excel-addin\Addin\bin\Release\xltrail64.dna" /Y
  - del "%APPVEYOR_BUILD_FOLDER%\excel-addin\Addin\bin\Release\xltrail.xll"
  - del "%APPVEYOR_BUILD_FOLDER%\excel-addin\Addin\bin\Release\xltrail64.xll"
  - ren "%APPVEYOR_BUILD_FOLDER%\excel-addin\Addin\bin\Release\xltrail_packed.xll" xltrail.xll
  - ren "%APPVEYOR_BUILD_FOLDER%\excel-addin\Addin\bin\Release\xltrail64_packed.xll" xltrail64.xll
  - dir "%APPVEYOR_BUILD_FOLDER%\excel-addin\Addin\bin\Release"
  - signtool sign /f scripts/windows/key.p12 /p %secure% git-xltrail-*.exe
  - iscc scripts\windows\inno-setup-git-xltrail-installer.iss
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "false")
      {
        Rename-Item -Path "git-xltrail-windows-0.0.0.exe" -NewName "git-xltrail-windows-$($env:APPVEYOR_REPO_COMMIT.substring(0,7)).exe"
      }
  - cmd: signtool sign /f scripts/windows/key.p12 /p %secure% git-xltrail-windows*.exe
  
test_script:
  - C:\Python36\python -m unittest discover src -vv
  - C:\Python36-x64\python -m unittest discover src -vv


artifacts:
  - path: git-xltrail-windows-*.exe
  - path: git-xltrail-x86.exe
  - path: git-xltrail-x64.exe
  - path: git-xltrail-diff-x86.exe
  - path: git-xltrail-diff-x64.exe
  - path: git-xltrail-merge-x86.exe
  - path: git-xltrail-merge-x64.exe
  - path: excel-addin\Addin\bin\Release\xltrail.xll
    name: xltrail.xll
  - path: excel-addin\Addin\bin\Release\xltrail64.xll
    name: xltrail64.xll

deploy:
- provider: GitHub
  release: $(APPVEYOR_REPO_TAG_NAME)
  description: 'Git xltrail $(APPVEYOR_REPO_TAG_NAME)'
  auth_token:
    secure: u1oi+34ucFzW+B5tKlGUMP2NjPISw4G61InbYVF3qYq6onAC4+rA92XRn+aDhMEW
  artifact: /git-xltrail-windows-.*\.exe/
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true

# on_finish:
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))