skip_branch_with_pr: true

install:
  - cinst InnoSetup -y
  - C:\Python36\Scripts\pip install -r requirements.txt
  - C:\Python36-x64\Scripts\pip install -r requirements.txt

build_script:
  - C:\Python36\Scripts\pyinstaller --onefile .\git-xltrail-diff.py --name git-xltrail-diff-x86.exe --version-file .\scripts\windows\git-xltrail-version-info.py --icon .\scripts\windows\git-xltrail-logo.ico
  - mv dist\git-xltrail-diff-x86.exe git-xltrail-diff-x86.exe
  - C:\Python36-x64\Scripts\pyinstaller --onefile .\git-xltrail-diff.py --name git-xltrail-diff-x64.exe --version-file .\scripts\windows\git-xltrail-version-info.py --icon .\scripts\windows\git-xltrail-logo.ico
  - mv dist\git-xltrail-diff-x64.exe git-xltrail-diff-x64.exe
  - C:\Python36\Scripts\pyinstaller --onefile .\git-xltrail.py --name git-xltrail-x86.exe --version-file .\scripts\windows\git-xltrail-version-info.py --icon .\scripts\windows\git-xltrail-logo.ico
  - mv dist\git-xltrail-x86.exe git-xltrail-x86.exe
  - C:\Python36-x64\Scripts\pyinstaller --onefile .\git-xltrail.py --name git-xltrail-x64.exe --version-file .\scripts\windows\git-xltrail-version-info.py --icon .\scripts\windows\git-xltrail-logo.ico
  - mv dist\git-xltrail-x64.exe git-xltrail-x64.exe

after_build:
  - iscc scripts\windows\inno-setup-git-xltrail-installer.iss
  - mv scripts\windows\git-xltrail-windows-0.01.exe git-xltrail-windows-0.0.1.exe

artifacts:
  - path: git-xltrail-diff-x86.exe
  - path: git-xltrail-diff-x64.exe
  - path: git-xltrail-x86.exe
  - path: git-xltrail-x64.exe
  - path: git-xltrail-windows-*.exe


# on_finish:
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))